### ISSUE TITLE
Table <tr>s don't create new lines

### ISSUE THREAD

**Issue by poshest** [andris9/nodemailer-html-to-text#2]
Table `<tr>`s aren't creating new line characters, and not even spaces, so you get `... some text</td></tr><tr><td>More text....` becoming `...some textMore text`.

Maybe it's supposed to be that way, but since tables are often the only way to make HTML emails look good, it would be good just to add line breaks for new rows.

**Comment by andris9** [comment]
The html to text conversion is done by the [html-to-text](https://www.npmjs.com/package/html-to-text) module. I upgraded the version of html-to-text to the latest with 95de958ac7498f6c27d9a9adfe8412d031b0bec8 so this should partly resolve the issue.
