### ISSUE TITLE
Remove inlined picture references

### ISSUE THREAD

**Issue by BridgeAR** [andris9/nodemailer-html-to-text#3]
If you add a inline picture to your html and generate the plain text from that the picture will be added to the plaintext e.g.: [cid:logo]. It would be nice to remove those entries as no one benefits from them in the plain version.
And since this is specific about nodemailer it's not an issue for html-to-text itself.

If you wish I'll submit a PR for this.

**Comment by andris9** [comment]
If you could create a PR it would be great
